run:
  timeout: 10m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
  disable:
    - gosec
    - goconst
    - gocyclo
    - bodyclose
    - prealloc
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  
  misspell:
    locale: US

issues:
  exclude-use-default: true
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 10