repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt
        language: system
        types: [go]
        args: [-w]
      
      - id: go-vet
        name: go vet
        entry: go
        language: system
        types: [go]
        args: [vet, ./...]
        pass_filenames: false
      
      - id: go-mod-tidy
        name: go mod tidy
        entry: go
        language: system
        args: [mod, tidy]
        pass_filenames: false
      
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint
        language: system
        types: [go]
        args: [run, --fix]
        pass_filenames: false
      
      - id: go-test
        name: go test
        entry: go
        language: system
        types: [go]  
        args: [test, -race, ./...]
        pass_filenames: false